[context.staging.environment]
  VUE_APP_API_URL="https://staging-we-are-mini-golf.herokuapp.com"

[context.master.environment]
  VUE_APP_API_URL="https://production-we-are-mini-golf.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200